---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.smc.serviceAccountName | default "smc-sa" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "siebel.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cgw.serviceAccountName | default "cgw-sa" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "siebel.labels" . | nindent 4 }}