apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: cm-siebel-image
  namespace: {{ .Release.Namespace }}
  labels: {{- include "siebel.labels" . | nindent 4 }}
spec:
  image: {{ template "siebel.image" . }}
  interval: 1m0s
  secretRef:
    name: customsecret

