apiVersion: v1
kind: Secret
metadata:
  name: siebel-controller-tls
  labels:
    app.kubernetes.io/name: metacontroller
type: Opaque
data:
  tls.crt: {{ .Files.Get "tls/tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "tls/tls.key" | b64enc }}
  ca.crt: {{ .Files.Get "tls/ca.crt" | b64enc }}