apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "metacontroller.fullname" . }}
  namespace: {{ include "metacontroller.namespace" . }}
  labels:
    {{- include "metacontroller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  serviceName: ''
  selector:
    matchLabels:
      {{- include "metacontroller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metacontroller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "metacontroller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "metacontroller.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SSL_CERT_FILE
            value: /certs/ca.crt
          livenessProbe:
            httpGet:
              port: {{ .Values.probes.port | default 8081 }}
              path: /healthz
          readinessProbe:
            httpGet:
              port: {{ .Values.probes.port | default 8081 }}
              path: /readyz
          command:
          - {{ .Values.command | default "/usr/bin/metacontroller" }}
          args:
            {{- toYaml .Values.commandArgs | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /certs/ca.crt
            name: siebel-controller-tls
            subPath: ca.crt
            readOnly: true
      volumes:
      - name: siebel-controller-tls
        secret:
          secretName: siebel-controller-tls
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
