replicaCount: 1
image:
  siebel_open_integration:
    registry: iad.ocir.io
    repository: siebeldev/cm/siebel_openint
    tag: latest
    imagePullPolicy: Always

imagePullSecrets:
  - ocirsecret
  - customsecret

siebelCerts:
  secretName: siebel-certs
  siebel_server_keystore_file_name: siebelserverkeystore.jks
  siebel_client_keystore_file_name: siebelclientkeystore.jks
  siebel_truststore_file_name: siebeltruststore.jks

service:
  type: LoadBalancer
  port: 443
  targetPort: 8433


  annotations:
    service.beta.kubernetes.io/oci-load-balancer-internal: "true"
    service.beta.kubernetes.io/oci-load-balancer-shape: flexible
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-subnet1: ocid1.subnet.oc1.iad.aaaaaaaabgu3ccycjph5iq635bgc74sndkawsle5szth74tovm3gt5lposiq

resources:
    limits:
      cpu: "1"
      memory: 8Gi
    requests:
      cpu: "0.5"
      memory: 2Gi

livenessProbe:
  port: 8433
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

coherence:
  enable: true
  clusterName: siebelcache
  clusterWKA: siebelcache-wka.coherence-server.svc
  wkaEndpoint: coherence-nodeport.coherence-server.svc.cluster.local

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
