# Default values for siebel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  busybox:
    registry: iad.ocir.io
    repository: idvw9hrofahp/siebel_repo/cm/base-builder
    tag: CM_26.3.0
    imagePullPolicy: Always
  configure:
    registry: iad.ocir.io
    repository: idvw9hrofahp/siebel_repo/cm/sieb-config
    tag: CM_26.6.0
    imagePullPolicy: Always
  dbutils:
    registry: iad.ocir.io
    repository: idvw9hrofahp/siebel_repo/cm/dbutils
    tag: CM_26.3.0
    imagePullPolicy: Always
  utils:
    registry: iad.ocir.io
    repository: idvw9hrofahp/siebel_repo/cm/utils
    tag: CM_26.3.0
    imagePullPolicy: Always

#Storage Information
storage:
  - storageClassName: oci-fss
    nfsServer: dx4c-dev-mt.sub3f36566ba.dx4cdev.oraclevcn.com
    nfsPath: /okepodspv/DEMO-CRM

dbInfo:
  dbTnsAlias: SIEBEL
  tnsconnectString: "(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = siebel-db)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = SIEBEL.localdomain)))"
  dbUser: sadmin
  dbPassword: ''
  tblo: SIEBEL
  tbloPassword: SIEBEL
  defaultTablespace: DATA
  defaultIndexspace: DATA
  SSEROLE: SSE_ROLE
      
ca:
  #ipAddress: 129.213.124.55
  clusterDns: svc.cluster.local

# it should come from other module
dbWallet:
  path: db_wallet

cgw:
  replicas: 3

imagePullSecrets: #Add additional secrets as required if accessing multiple registries, create them prior to helm install
  - ocirsecret
  - customsecret

lang:
  primaryLang: ENU
  otherLangs: ''

securityContext:
  runAsGroup: 1000
  runAsUser: 1000
  fsGroup: 1000

namespaceEnvid: siebel-jbb175

git:
  git_user: "git_user"
  git_accesstoken: "git_accesstoken"
  git_helm_repo_url: "git_helm_repo_url"
  git_helm_repo_branch: "main"
  git_selfsigned_cacert: "/home/opc/certs/ca.crt"

enableFixMount: true

