# siebel-secrets kubernetes yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: openint-common-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "1"
type: Opaque
data:
  TARGET_REGISTRY_PASSWORD: {{ .Values.registry.target.registry_password | b64enc }}
  TARGET_REGISTRY_URL: {{ .Values.registry.target.registry_url | b64enc }}
  TARGET_REGISTRY_USER: {{ .Values.registry.target.registry_user | b64enc }}
  SOURCE_REGISTRY_PASSWORD: {{ .Values.registry.source.registry_password | b64enc }}
  SOURCE_REGISTRY_URL: {{ .Values.registry.source.registry_url | b64enc }}
  SOURCE_REGISTRY_USER: {{ .Values.registry.source.registry_user | b64enc }}
