{{ if .Values.envInfo.createBlockVolume }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaimConfig.name }}
  labels: {{- include "siebel.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.blockVolumeConfig.storageClassName }}
  accessModes: {{ .Values.persistentVolumeClaimConfig.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaimConfig.storageSize }}
{{ end }}