{{ if .Values.envInfo.createBlockVolume }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ .Values.blockVolumeConfig.storageClassName }}"
  labels: {{- include "siebel.labels" . | nindent 4 }}
provisioner: blockvolume.csi.oraclecloud.com
parameters:
  vpusPerGB: "{{ .Values.blockVolumeConfig.vpusPerGb }}"
  attachment-type: "{{ .Values.blockVolumeConfig.attachmentType }}"
reclaimPolicy: "{{ .Values.blockVolumeConfig.reclaimPolicy }}"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: {{ .Values.blockVolumeConfig.allowVolumeExpansion }}
{{ end }}