{{- if and (eq .Values.envInfo.ociDeployment "oc3") (.Values.envInfo.caCrtFilename) }}
apiVersion: v1
kind: Secret
metadata:
  name: ca-certificate-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "siebel.labels" . | nindent 4 }}
    app: siebel  
type: Opaque
data:
{{- $path := printf "oci/*" }}
{{ (.Files.Glob $path).AsSecrets | nindent 2  }}
{{- end }}