---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsspv-cm
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "siebel.labels" . | nindent 4 }}
spec:
  storageClassName: oci-fss
  # .capacity.storage is a mandatory field in the k8s, but not in oke. So provide a dummy/placeholder value
  # https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengcreatingpersistentvolumeclaim_Provisioning_PVCs_on_FSS.htm
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  mountOptions:
  - nosuid
  nfs:
    server: {{ .Values.envInfo.mountTargetIp }}
    path: {{ .Values.envInfo.exportPath | quote }}
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsspvc-cm
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "siebel.labels" . | nindent 4 }}
spec:
  storageClassName: oci-fss
  accessModes:
    - ReadWriteMany
  resources:
    # .requests.storage is a mandatory field in the k8s, but not in oke. So provide a dummy/placeholder value
    # https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengcreatingpersistentvolumeclaim_Provisioning_PVCs_on_FSS.htm
    requests:
      storage: 10Gi
  volumeName: fsspv-cm