{{- $root := . -}}
{{- $useByofs := .Values.envInfo.useByofs | default false -}}
{{- range $index, $val := .Values.storage }}
{{- if eq $val.isCompleted false }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sfs-job-{{ $index }}
  labels: {{- include "siebel.labels" $ | nindent 4 }}
spec:
  template:
    spec:
      serviceAccountName: {{ $.Values.serviceAccount.name }}
      securityContext:
        runAsUser: {{ $.Values.securityContext.runAsUser }}
        runAsGroup: 0
        fsGroup: {{ $.Values.securityContext.fsGroup }}
      initContainers:
      - name: create-fs-dir
        imagePullPolicy: {{ $.Values.image.pullPolicy | default "IfNotPresent" }}
        image: {{ template "busybox.image" $root }}
{{- if not $useByofs }}
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
            add:
            - CHOWN
{{- end }}
        env:
        - name: runAsUser
          value: {{ int64 $.Values.securityContext.runAsUser | quote }}
        - name: runAsGroup
          value: "0"
        command:
          - sh
          - -c
          - |
            set -e
            fs_root=/sfs{{ $index }}/{{ $.Release.Namespace | upper }}
            echo "Creating ${fs_root} directory"
            umask 0002
            mkdir -p "${fs_root}/FS"
            chown -R "$runAsUser:0" "${fs_root}"
            ls -ltrh /sfs{{ $index }}/{{ $.Release.Namespace | upper }}
        volumeMounts:
        - name: sfs-storage-{{ $index }}
          mountPath: /sfs{{ $index }}
      containers:
      - name: sfs-{{ $index }}
        image: {{ template "scm.image" $ }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        env:
        - name: FS_INDEX
          value: {{ $index | quote }}
        - name: oci_deployment
          value: {{ $.Values.envInfo.ociDeployment | lower | quote }}
        {{ if $.Values.envInfo.caCrtFilename }}
        - name: ca_cert_filepath
          value: /home/opc/{{ $.Values.envInfo.caCrtFilename }}
        {{- end }}
        command:
          - sh
          - -c
          - source /home/opc/.bashrc;
            cd /home/opc/siebel-cloud-manager/scripts/cmapp;
            python src/shift-siebel-fs.py -f /home/opc/cmapp/{{ $.Values.envInfo.namespace }}/siebel/environments/{{ $.Values.envInfo.envId }}_environment.yaml -a shift-fs;
        volumeMounts:
        - name: sfs-storage-{{ $index }}
          mountPath: /sfs{{ $index }}
          subPath: {{ $.Release.Namespace | upper }}/FS
        - name: cm-storage
          mountPath: /home/opc/cmapp
          subPath:
        {{ if $.Values.artifactory.tokenSecretName }}
        - name: artifactory-token
          mountPath: {{ $.Values.artifactory.tokenMountPath }}
          subPath: {{ $.Values.artifactory.tokenSecretKey }}
          readOnly: true
        {{ end }}
{{ if $.Values.envInfo.createBlockVolume }}
        - name: sfs-temp-storage-{{ $index }}
          mountPath: {{ $.Values.blockVolumeConfig.localMountDir }}
{{ end }}
        {{ if $.Values.envInfo.caCrtFilename }}
        - name: ca-crt
          mountPath: /home/opc/{{ $.Values.envInfo.caCrtFilename }}
          subPath: {{ $.Values.envInfo.caCrtFilename }}
        {{- end }}
      restartPolicy: OnFailure
      volumes:
        - name: sfs-storage-{{ $index }}
          persistentVolumeClaim:
            claimName: fsspvc-sfs-{{ $index }}
            readOnly: false
        - name: cm-storage
          persistentVolumeClaim:
            claimName: fsspvc-cm
            readOnly: false
        {{ if $.Values.artifactory.tokenSecretName }}
        - name: artifactory-token
          secret:
            defaultMode: 0400
            secretName: {{ $.Values.artifactory.tokenSecretName }}
        {{ end }}
{{ if $.Values.envInfo.createBlockVolume }}
        - name: sfs-temp-storage-{{ $index }}
          persistentVolumeClaim:
            claimName: {{ $.Values.persistentVolumeClaimConfig.name }}
            readOnly: false
{{ end }}
        {{ if $.Values.envInfo.caCrtFilename }}
        - name: ca-crt
          secret:
            defaultMode: 420
            secretName: ca-certificate-secret
        {{- end }}
      imagePullSecrets:
        {{- range $.Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
  backoffLimit: 4
---
{{ end }}
{{- end -}}
