---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ses.serviceAccountName | default "ses-sa" }}
  namespace: {{ .Release.Namespace }}
  labels:
    labels: {{- include "siebel.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sai.serviceAccountName | default "sai-sa" }}
  namespace: {{ .Release.Namespace }}
  labels:
    labels: {{- include "siebel.labels" . | nindent 4 }}