apiVersion: v1
kind: Secret
metadata:
  name: coherence-siebel-certs
  labels:
    app: coherence-server
  annotations:
    ## This is what defines this resource as a hook. Without this line, the job is considered part of the release
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
    siebelserverkeystore.jks: {{ .Files.Get "keystore/siebelserverkeystore.jks"  | b64enc }}
    siebelclientkeystore.jks: {{ .Files.Get "keystore/siebelclientkeystore.jks"  | b64enc }}
    siebeltruststore.jks: {{ .Files.Get "keystore/siebeltruststore.jks"  | b64enc }}

