artifactory:
  tokenMountPath: /home/opc/config/artifactory_token
  tokenSecretKey: ARTIFACTORY_TOKEN
  tokenSecretName: ''
blockVolumeConfig:
  allowVolumeExpansion: true
  attachmentType: iscsi
  localMountDir: /bv
  reclaimPolicy: Delete
  storageClassName: oci-bv-custom
  storageInGbs: 200
  vpusPerGb: 30
envInfo:
  createBlockVolume: false
  envId: JBB175
  exportPath: /siebelfs
  mountTargetIp: 10.4.2.18
  namespace: SCM
  ociDeployment: public
  useByofs: true
image:
  busybox:
    registry: iad.ocir.io
    repository: idvw9hrofahp/siebel_repo/cm/base-builder
    tag: CM_26.3.0
  pullPolicy: Always
  registry: iad.ocir.io
  repository: idvw9hrofahp/siebel_repo/cm/server
  tag: CM_26.6.0
imagePullSecrets:
- ocirsecret
namespaceEnvid: siebel-jbb175
persistentVolumeClaimConfig:
  accessModes:
  - ReadWriteOnce
  name: sfs-pvc
  storageSize: 50Gi
securityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsUser: 1000
serviceAccount:
  name: sfs-sa
storage:
- isCompleted: false
  nfsPath: /siebelfs
  nfsServer: 10.4.2.18
  storageClassName: oci-fss
