apiVersion: v1
kind: Service
metadata:
  name: coherence-nodeport-{{ .Values.coherence.clusterName }}
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    coherenceCluster: {{ .Values.coherence.clusterName }}
  ports:
{{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
#      {{- if eq $.Values.service.type "NodePort" }}
#      nodePort: {{ .nodePort }}
#      {{- end }}
{{- end }}

